# è¨­ç½®æ¦‚ç‡

# 0.0 - 1.0
# 0.2 == 20%
EnchantItem: 0.2
EnchantBook: 0.5

# è¨­ç½®æç¤º ï¼ˆMiniMessage æ”¯æ´ï¼‰ %s ç‚ºå†…éƒ¨è®Šé‡ è«‹å‹¿åˆªé™¤
Message: "<gold>[<aqua><bold>ğŸŸ<reset><gold>] <aqua>ä½ çš„ %s è¢« BallKing åƒæ‰äº†!"