# è¨­ç½®æ¦‚ç‡

# 0.0 - 1.0
# 0.2 == 20%
EnchantItem: 0.2
EnchantBook: 0.5

# æˆ˜åˆ©å“å¹¸è¿åº¦ç­‰çº§ è®¾ç½®ä¸º0è‡³-1ä¸ºéšæœº
DefaultLootingLevel: 1

# å®Œå…¨æ›¿æ¢, è®¾ç½®ä¸º true åˆ™å®Œå…¨ä½¿ç”¨ LootItems è®¾ç½®çš„ç‰©å“
FullReplacement: false
# æ›¿ä»£çš„ç‰©å“
LootItems:
  salmon:
    weight: 100 # æƒé‡
    item:
      ==: org.bukkit.inventory.ItemStack
      v: 3465 # Keep this
      type: SALMON # ç‰©å“ID

# è¿›è¡Œæ¦‚ç‡æ›¿æ¢çš„æç¤º (æ”¯æŒ MiniMessage)
# <item> - åŸç‰©å“
# <item_replaced> - è¢«æ›¿æ¢çš„æ–°ç‰©å“
MessageOnReplace: false
Message: "<gold>[<aqua><bold>ğŸŸ<reset><gold>] <aqua>ä½ çš„ <item> è¢«é±¼åƒæ‰äº†!"